# Generated by Django 6.0.5 on 2026-05-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_company', models.CharField()),
                ('flight_name', models.CharField()),
                ('flight_no', models.IntegerField()),
                ('from_city', models.CharField()),
                ('to_city', models.CharField()),
                ('depature_time', models.IntegerField()),
                ('depature_date', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
