# Generated by Django 6.0.5 on 2026-05-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_company', models.CharField()),
                ('flight_name', models.CharField()),
                ('flight_no', models.IntegerField()),
                ('from_city', models.CharField()),
                ('to_city', models.CharField()),
                ('depature_time', models.IntegerField()),
                ('depature_date', models.IntegerField()),
                ('price', models.IntegerField()),
                ('passenger_name', models.CharField()),
                ('email', models.CharField()),
                ('phone_no', models.IntegerField()),
                ('adhar_no', models.IntegerField()),
                ('age', models.IntegerField()),
                ('seat_class', models.CharField()),
                ('seat_no', models.IntegerField()),
            ],
        ),
    ]
