# Generated by Django 6.0.5 on 2026-05-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_bookingmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='depature_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='depature_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='flightmodel',
            name='depature_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='flightmodel',
            name='depature_time',
            field=models.TimeField(),
        ),
    ]
