# Generated by Django 6.0.5 on 2026-05-29 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_bookingmodel_depature_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='adhar_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='flight_company',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='flight_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='from_city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='passenger_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='phone_no',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='seat_class',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='to_city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='flightmodel',
            name='flight_company',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='flightmodel',
            name='flight_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='flightmodel',
            name='from_city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='flightmodel',
            name='to_city',
            field=models.CharField(max_length=100),
        ),
    ]
