# Generated by Django 6.0.5 on 2026-05-29 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_bookingmodel_adhar_no_alter_bookingmodel_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_company', models.CharField(max_length=100)),
                ('flight_name', models.CharField(max_length=100)),
                ('flight_no', models.IntegerField()),
                ('from_city', models.CharField(max_length=100)),
                ('to_city', models.CharField(max_length=100)),
                ('depature_time', models.TimeField()),
                ('depature_date', models.DateField(null=True)),
                ('price', models.IntegerField()),
                ('passenger_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=15)),
                ('adhar_no', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('seat_class', models.CharField(max_length=50)),
                ('seat_no', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='depature_date',
            field=models.DateField(null=True),
        ),
    ]
